version: '3'
services:
    app:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: larapel_test
        ports:
            - '8089:80'
        volumes:
            - '.:/var/www/html'
        links:
            - mysql
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${DB_PORT}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'